# Site settings
title: Rx Android Architecture
email: timo.tuominen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/rx-android-architecture" # the subpath of your site, e.g. /blog/
url: "http://tehmou.github.io" # the base hostname & protocol for your site
twitter_username: tehmou
github_username:  tehmou

# Build settings
markdown: kramdown
